type lookupTableType = {
  [key: string]: {
    project: string;
    subcategory: string;
    transactionType: string;
  };
};

export const lookupTable: lookupTableType = {
  "APTOS COMMISSION-REWARD": {
    project: "Aptos",
    subcategory: "Aptos",
    transactionType: "Commission",
  },
  "PAYMENT BÖRSE STUTTGART": {
    project: "BSG",
    subcategory: "BSG",
    transactionType: "Commission",
  },
  "ETH ORACLE-REWARD": {
    project: "Chainlink",
    subcategory: "ETH",
    transactionType: "Rewards",
  },
  "POLYGON ORACLE-REWARD": {
    project: "Chainlink",
    subcategory: "Polygon",
    transactionType: "Rewards",
  },
  "LIDO COMMISSION-REWARD": {
    project: "Lido",
    subcategory: "Lido",
    transactionType: "Commission",
  },
  OPERATIONS: {
    project: "Operations",
    subcategory: "Operations",
    transactionType: "Operations",
  },
  "SOLANA BEACH BLOCK-REWARD": {
    project: "Solana",
    subcategory: "Beach",
    transactionType: "Block-Rew.",
  },
  "SOLANA BEACH COMMISSION-REWARD": {
    project: "Solana",
    subcategory: "Beach",
    transactionType: "Inflationary-Rew.",
  },
  "SOLANA BEACH MEV-REWARD": {
    project: "Solana",
    subcategory: "Beach",
    transactionType: "MEV",
  },
  "SOLANA COMMISSION-REWARD": {
    project: "Solana",
    subcategory: "Main",
    transactionType: "Inflationary-Rew.",
  },
  "SOLANA BLOCK REWARD": {
    project: "Solana",
    subcategory: "Main",
    transactionType: "Block-Rew.",
  },
  "SOLANA MEV-REWARDS": {
    project: "Solana",
    subcategory: "Main",
    transactionType: "MEV",
  },
  "SOLANA SQUADS STAKING-REWARD": {
    project: "Solana",
    subcategory: "Squads",
    transactionType: "Staking Rew.",
  },
  "SOLANA SF SQUADS MEV-REWARD": {
    project: "Solana",
    subcategory: "Squads",
    transactionType: "MEV",
  },
  "SOLANA SUPERTEAM COMMISSION-REWARD": {
    project: "Solana",
    subcategory: "Superteam",
    transactionType: "Inflationary-Rew.",
  },
  "SOLANA SUPERTEAM BLOCK-REWARD": {
    project: "Solana",
    subcategory: "Superteam",
    transactionType: "Block-Rew.",
  },
  "SOLANA SUPERTEAM MEV-REWARD": {
    project: "Solana",
    subcategory: "Superteam",
    transactionType: "MEV",
  },
  "SUI COMMISSION-REWARD": {
    project: "Sui",
    subcategory: "Sui",
    transactionType: "Commission",
  },
  "SUI STAKING REWARD": {
    project: "Sui",
    subcategory: "Sui",
    transactionType: "Staking Rew.",
  },
  "CELESTIA COMMISSION-REWARD": {
    project: "Celestia",
    subcategory: "Celestia",
    transactionType: "Commission",
  },
  "CELESTIA STAKING-REWARD": {
    project: "Celestia",
    subcategory: "Celestia",
    transactionType: "Staking Rew.",
  },
};

type kontoTableType = {
  [key: string]: string;
};

export const kontoTable: kontoTableType = {
  "440000": "Revenue",
  "469000": "Revenue",
  "590000": "COGS",
  "590001": "COGS",
  "590002": "COGS",
  "483000": "Other operating income",
  "484700": "Other operating income",
  "494600": "Other operating income",
  "494700": "Other operating income",
  "600000": "Personnel costs",
  "601000": "Personnel costs",
  "602000": "Personnel costs",
  "602100": "Personnel costs",
  "602400": "Personnel costs",
  "603500": "Personnel costs",
  "603600": "Personnel costs",
  "603900": "Personnel costs",
  "606000": "Personnel costs",
  "606900": "Personnel costs",
  "607100": "Personnel costs",
  "607200": "Personnel costs",
  "607300": "Personnel costs",
  "609000": "Personnel costs",
  "611000": "Personnel costs",
  "612000": "Personnel costs",
  "613000": "Personnel costs",
  "616000": "Personnel costs",
  "617000": "Personnel costs",
  "617100": "Personnel costs",
  "631000": "Room & Rental costs",
  "632500": "Room & Rental costs",
  "634500": "Room & Rental costs",
  "640000": "Insurance & Contribution costs",
  "642000": "Insurance & Contribution costs",
  "643000": "Insurance & Contribution costs",
  "643100": "Insurance & Contribution costs",
  "643600": "Insurance & Contribution costs",
  "643700": "Insurance & Contribution costs",
  "652000": "Vehicle costs",
  "653000": "Vehicle costs",
  "654000": "Vehicle costs",
  "656500": "Vehicle costs",
  "657000": "Vehicle costs",
  "660000": "Advertising & Travel costs",
  "660500": "Advertising & Travel costs",
  "661100": "Advertising & Travel costs",
  "662100": "Advertising & Travel costs",
  "663000": "Advertising & Travel costs",
  "664000": "Advertising & Travel costs",
  "664300": "Advertising & Travel costs",
  "664400": "Advertising & Travel costs",
  "666000": "Advertising & Travel costs",
  "666300": "Advertising & Travel costs",
  "666400": "Advertising & Travel costs",
  "649500": "Repair & Maintenance costs",
  "630300": "Other operating costs",
  "630301": "Personnel costs",
  "630302": "Other operating costs",
  "630303": "Advertising & Travel costs",
  "680000": "Other operating costs",
  "681000": "Internet costs",
  "681500": "Other operating costs",
  "682000": "Other operating costs",
  "682100": "Other operating costs",
  "682200": "Other operating costs",
  "682500": "Legal & Consulting costs",
  "682700": "Legal & Consulting costs",
  "683000": "Legal & Consulting costs",
  "683500": "Data Center costs",
  "683700": "License costs",
  "684500": "Other operating costs",
  "685000": "Other operating costs",
  "685500": "Other operating costs",
  "688100": "Other operating costs",
  "730200": "Interest expenses",
  "730400": "Interest expenses",
  "730800": "Interest expenses",
  "731800": "Interest expenses",
  "702000": "Interest income",
  "493200": "Other neutral income",
  "497200": "Other neutral income",
  "760300": "Taxes",
  "761000": "Taxes",
  "730000": "Interest expenses",
  "433800": "Revenue",
  "763000": "Taxes",
  "763300": "Taxes",
  "768500": "Vehicle costs",
  "649000": "Repair & Maintenance costs",
  "622000": "Depreciation",
};
